### ISSUE TITLE
Error: tcpip::Socket::accept() Unable to create listening socket: Address already in use

### ISSUE THREAD

**Issue by luckywlj** [docwza/sumolights#22]
Hi, I am pleasure to read your paper and interested in your program project. I configure the running environment on Ubuntu18.04 and try to run the experiments. My experiment environment  is as follows:
Ubuntu18.04, Anaconda3-5.3.1-Linux-x86_64.sh, python3.7.5, tensorflow1.14.0, matplotlib3.1.1, sumo-1.12.0.
When I run "./train_dqn.sh", there is an error as follow:
![2022-04-22 22-40-36 的屏幕截图](https://user-images.githubusercontent.com/53700751/164874512-65c937b4-62c1-4cb2-b49b-55cbcaecc0ab.png)
I check the traci docs and don not find the connect() function. I add an configuration in .bashrc as "export LIBSUMO_AS_TRACI=1" and "source ~/.bashrc". But this error still exists.
I do not the reason of the problem. Could you help me?

**Comment by docwza** [comment]
I believe AttributeError is caused by the fact that you have set the LIBSUMO_AS_TRACI=1 which makes the traci.connect(port) unnecessary. Instead, you should just call traci.start(['sumo', '-c', PATH_TO_SUMO_CONFIG]) or unset the LIBSUMO_AS_TRACI environment variable and then you can use the connect function.

I'm going to mark this issue as resolved. If you still have the problem reopen an issue.
